spring.application.name=event-platform
server.port=${PORT:8080}

spring.datasource.url=${JDBC_DATABASE_URL:jdbc:h2:mem:eventdb}
spring.datasource.driverClassName=${DB_DRIVER:org.h2.Driver}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:password}
spring.jpa.database-platform=${DB_PLATFORM:org.hibernate.dialect.H2Dialect}
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Thymeleaf
spring.thymeleaf.cache=false

# Security
logging.level.org.springframework.security=INFO
